BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_mile
            text: ""
        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.1, 1)
            Button:
                size_hint: (1, 0.5)
                text: "up"
                on_press: app.up_or_down(up_or_down = 1)
            Button:
                size_hint: (1, 0.5)
                text: "down"
                on_press: app.up_or_down(up_or_down = -1)
    BoxLayout:
        id: convert_to_km
        orientation: "vertical"
        Button:
            text: "convert miles to KM"
            on_press: app.convert_miles_to_km()
        BoxLayout:
            Label:
                id: km_output
                color: (1,1,0,1)
                text:



