BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: '7'
            font_size: 48
            multiline: False
        Button:
            orientation: 'horizontal'
            text: 'Square'
        # the following line specifies the function in the app class to call when the button is pressed
            on_press: app.handle_calculate(input_number.text)
        Label:
            orientation: 'horizontal'
            id: output_label
            font_size: 48
            color: (1, 35, 1, 1)


    BoxLayout:
        Label:
            text: "Enter a number and press Square."
